import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Main from '../layout/main'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="//db.onlinewebfonts.com/c/56bd6cd7c8d4b467838b5b2971fd6ee5?family=HarmoniaSansW01-Semibold" rel="stylesheet" type="text/css"/>
      </Head>
      <Main/>

      <main className={styles.main}>
      </main>
    </div>
  )
}
